name: Cypress Tests

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create env file
        run: | 
         echo "${{ secrets.ENV}}" > .env.local
      
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
          
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/screenshots
